In [12]:
import pandas as pd

In [2]:
props = pd.read_csv("http://www.firstpythonnotebook.org/_static/committees.csv")

In [3]:
props.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
0,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,382,1374469,YES ON PROPOSITION 51 - CALIFORNIANS FOR QUALI...,SUPPORT
1,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,383,1220380,COMMUNITY COLLEGE FACILITY COALITION ISSUES CO...,SUPPORT
2,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,384,1282321,TORLAKSON'S INVEST IN CALIFORNIA A BALLOT MEAS...,SUPPORT
3,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,385,1382843,CALIFORNIA TAXPAYERS AND EDUCATORS OPPOSED TO ...,OPPOSE
4,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,386,1362973,YES ON PROPOSITION 52 - A COALITION OF CALIFOR...,SUPPORT

In [4]:
props.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
ocd_prop_id               102 non-null object
calaccess_prop_id         102 non-null int64
ccdc_prop_id              102 non-null int64
prop_name                 102 non-null object
ccdc_committee_id         102 non-null int64
calaccess_committee_id    102 non-null int64
committee_name            102 non-null object
committee_position        102 non-null object
dtypes: int64(4), object(4)
memory usage: 6.4+ KB

In [5]:
contribs=pd.read_csv("http://www.firstpythonnotebook.org/_static/contributions.csv")

In [6]:
contribs.head()

,calaccess_committee_id,committee_name,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,BERGMAN,GRETCHEN,SPRING VALLEY,CA,91978,A NEW PATH,EXECUTIVE DIRECTOR,False,84.0
1,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,KAHLE,MYRNA,SAN DIEGO,CA,92109,NATIONAL SCHOOL DISTRICT,TEACHER,False,35.0
2,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-15,MCDEVITT,LEO,ESCONDIDO,CA,92025,LIFE IONIZERS,SEO/CONTENT MANAGER,False,198.0
3,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-08-10,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,False,-50.0
4,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-26,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,True,50.0

In [7]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [8]:
props.prop_name.value_counts().reset_index()

                                                index  prop_name
0   PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE...         13
1   PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...         12
2   PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...         11
3   PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...          9
4   PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...          8
5   PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...          7
6   PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...          7
7   PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES ...          6
8   PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...          4
9   PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...          4
10  PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUT...          4
11  PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...          4
12  PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...          4
13  PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...          3
14  PROPOSITION 061- STATE PRESCRIPTION DRUG PURCH...          3
15  PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH ...          2
16  PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...          1

In [9]:
contribs.amount.value_counts().reset_index().head()

     index  amount
0   287.08   28612
1   100.00    7604
2    25.00    3749
3    50.00    3184
4  1000.00     974

In [10]:
contribs.contributor_occupation.value_counts().reset_index().head()

                  index  contributor_occupation
0  CORRECTIONAL OFFICER                   28617
1               RETIRED                    3795
2            UNEMPLOYED                    2630
3          NOT EMPLOYED                    2500
4              ATTORNEY                    1364

In [14]:
props.prop_name.value_counts()

PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE CRIMINAL PROCEEDINGS AND SENTENCING. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                           13
PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTHCARE, TOBACCO USE PREVENTION, RESEARCH, AND LAW ENFORCEMENT. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.    12
PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE.                                                                                                   11
PROPOSITION 066- DEATH PENALTY. PROCEDURES. INITIATIVE STATUTE.                                                                                                 9
PROPOSITION 055 - TAX EXTENSION TO FUND EDUCATION AND HEALTHCARE. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                          8
PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON SINGLE-USE PLASTIC BAGS.                                                                                         7
PROPOSITION 062- DEATH PENALTY. INITIATIVE STATUTE.                                                                                                             7
PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES OF 2016), ALLEN. CAMPAIGN FINANCE: VOTER INSTRUCTION                                                              6
PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOTER APPROVAL. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                                 4
PROPOSITION 054 - LEGISLATURE. LEGISLATION AND PROCEEDINGS. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                                                    4
PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUTES OF 2014), LARA. ENGLISH LANGUAGE EDUCATION                                                                     4
PROPOSITION 063- FIREARMS. AMMUNITION SALES. INTIATIVE STATUTE.                                                                                                 4
PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-12 SCHOOL AND COMMUNITY COLLEGE FACILITIES. INITIATIVE STATUTORY AMENDMENT.                                       4
PROPOSITION 052 - STATE FEES ON HOSPITALS. FEDERAL MEDI-CAL MATCHING FUNDS. INITIATIVE STATUTORY AND CONSTITUTIONAL AMENDMENT.                                  3
PROPOSITION 061- STATE PRESCRIPTION DRUG PURCHASES. PRICING STANDARDS. INITIATIVE STATUTE.                                                                      3
PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH REQUIREMENTS. INITIATIVE STATUTE.                                                                                 2
PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INITIATIVE STATUTE.                                                                                                   1
Name: prop_name, dtype: int64

In [17]:
prop = props[props.prop_name == "PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE."]

In [18]:
prop.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
74,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT
75,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,457,1382525,NEW APPROACH PAC (MPO),SUPPORT
76,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,458,1376077,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",SUPPORT
77,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,459,1382568,"PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...",OPPOSE
78,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,460,1371855,"MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64",SUPPORT

In [19]:
prop.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11 entries, 74 to 84
Data columns (total 8 columns):
ocd_prop_id               11 non-null object
calaccess_prop_id         11 non-null int64
ccdc_prop_id              11 non-null int64
prop_name                 11 non-null object
ccdc_committee_id         11 non-null int64
calaccess_committee_id    11 non-null int64
committee_name            11 non-null object
committee_position        11 non-null object
dtypes: int64(4), object(4)
memory usage: 792.0+ bytes

In [20]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [22]:
merged = pd.merge(prop, contribs, on="calaccess_committee_id")

In [23]:
merged.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-02-04,BRADEN QUIGLEY,LAURA,SACRAMENTO,CA,95825,LBQ STRATEGIES,CONSULTANT,False,100.0
1,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
2,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-29,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
3,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-03-28,"CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...",NaN,IRVINE,CA,92618,NaN,NaN,False,250000.0
4,ocd-contest/232cb72c-1b11-4293-b4e2-a181e80d172e,1381868,83,PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...,456,1381808,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",SUPPORT,"YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...",2038581,2016-01-05,DRUG POLICY ACTION,NaN,NEW YORK,NY,10001,NaN,NaN,False,250000.0

In [24]:
merged.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 860 entries, 0 to 859
Data columns (total 20 columns):
ocd_prop_id                     860 non-null object
calaccess_prop_id               860 non-null int64
ccdc_prop_id                    860 non-null int64
prop_name                       860 non-null object
ccdc_committee_id               860 non-null int64
calaccess_committee_id          860 non-null int64
committee_name_x                860 non-null object
committee_position              860 non-null object
committee_name_y                860 non-null object
calaccess_filing_id             860 non-null int64
date_received                   860 non-null object
contributor_lastname            860 non-null object
contributor_firstname           750 non-null object
contributor_city                860 non-null object
contributor_state               860 non-null object
contributor_zip                 860 non-null object
contributor_employer            657 non-null object
contributor_occupation          742 non-null object
contributor_is_self_employed    860 non-null bool
amount                          860 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 135.2+ KB

In [25]:
merged.amount.sum()

35177017.640000001

In [26]:
merged.committee_position.value_counts()

SUPPORT    762
OPPOSE      98
Name: committee_position, dtype: int64

In [27]:
support = merged[merged.committee_position == "SUPPORT"]

In [28]:
oppose = merged[merged.committee_position == "OPPOSE"]

In [29]:
support.amount.sum()

32675806.0

In [30]:
oppose.amount.sum()

2501211.6400000001

In [31]:
support.amount.sum()/merged.amount.sum()

0.92889642704798669

In [36]:
merged.groupby("committee_name_x").amount.sum().reset_index().sort_values("amount", ascending=False)

                                     committee_name_x       amount
10  YES ON 64, CALIFORNIANS TO CONTROL, REGULATE A...  15734047.00
4        FUND FOR POLICY REFORM (NONPROFIT 501(C)(4))   6140000.00
3   DRUG POLICY ACTION - NON PROFIT 501C4, YES ON ...   4470000.00
7                              NEW APPROACH PAC (MPO)   3865000.00
9   SAM ACTION, INC., A COMMITTEE AGAINST PROPOSIT...   1364000.00
8   PUBLIC AND MENTAL HEALTH ADVOCATES AGAINST 64,...   1130930.00
1   CALIFORNIANS FOR RESPONSIBLE MARIJUANA REFORM,...    860470.00
2   CALIFORNIANS FOR SENSIBLE REFORM, SPONSORED BY...    850000.00
5   MARIJUANA POLICY PROJECT OF CALIFORNIA, YES ON 64    739200.00
0          ADULT USE CAMPAIGN FOR PROPOSITION 64; THE     17089.00
6                         MOMS STRONG AGAINST PROP 64      6281.64

In [38]:
merged.groupby(["contributor_firstname", "contributor_lastname", "committee_position"]).amount.sum().reset_index().sort_values("amount", ascending=False)

,contributor_firstname,contributor_lastname,committee_position,amount
483,SEAN,PARKER AND AFFILIATED ENTITIES,SUPPORT,7250000.0
482,SEAN,PARKER,SUPPORT,1500000.0
281,JULIE,SCHAUER,OPPOSE,1364000.0
108,DANIEL,LEWIS,SUPPORT,1250000.0
194,HENRY,VAN AMERINGEN,SUPPORT,1000000.0
405,NICHOLAS,PRITZKER,SUPPORT,900000.0
421,PETER,THIEL,SUPPORT,300000.0
456,ROGER,JENKINS,SUPPORT,75000.0
23,ANGELA,HOWARD,SUPPORT,65000.0
322,LAWRENCE,HESS,SUPPORT,30000.0
221,JASON,POST,SUPPORT,10000.0
460,ROGER B.,MCNAMEE,SUPPORT,10000.0
548,ZACHARY PYM,WILLIAMS,SUPPORT,10000.0
239,JEREMY,ZACHARY,SUPPORT,7500.0
440,ROBERT,ADAMS,OPPOSE,6500.0
320,LAURIE,BENENSON,SUPPORT,5000.0
63,CAMILLA,FIELD,SUPPORT,5000.0
375,MICHAEL,DEAN,OPPOSE,5000.0
361,MARY QUINN,DELANEY,SUPPORT,5000.0
488,SHARON K.,CHRISTIE,SUPPORT,5000.0
515,TERRY,TURNER,SUPPORT,3664.0
301,KHURSHID,KHOJA,SUPPORT,3300.0
277,JULI,CROCKETT,SUPPORT,3000.0
149,DOUG,LANPHERE,SUPPORT,2920.0
76,CHARLES,ROVEN,SUPPORT,2500.0
158,EMILY,PAXHIA,SUPPORT,2500.0
414,PATRICK,MCMANAMON,SUPPORT,2500.0
507,STEVEN,PERSKY,SUPPORT,2500.0
382,MICHAEL,STEINMETZ,SUPPORT,2500.0
377,MICHAEL,KLEIN,SUPPORT,2500.0
...,...,...,...,...
75,CHARLES,LOVE,SUPPORT,100.0
191,GRETCHEN,BERGMAN,SUPPORT,84.0
387,MICHELLE,WOLFF,SUPPORT,84.0
385,MICHELLE,SEXTON,SUPPORT,84.0
189,GREG,SMITH,SUPPORT,75.0
389,MIKE,BARNETT,SUPPORT,50.0
534,WENDY,COLTON,SUPPORT,50.0
168,ETHAN,BROOKES,SUPPORT,50.0
85,CHRISTINE A.,PORTER,SUPPORT,50.0
459,ROGER,TOWER,SUPPORT,50.0
492,SKIP,ROACHE,SUPPORT,50.0
335,LJUBOMIR,BUTUROVIC,SUPPORT,50.0
418,PETER,KIRSCH,SUPPORT,50.0
326,LEONARD,KAUFMANN,SUPPORT,50.0
104,DANA,HIRSCH,SUPPORT,50.0
105,DANIEL,DODSON,SUPPORT,50.0
125,DAVID,MURRAY,SUPPORT,50.0
272,JOSH,KLEYMEYER,SUPPORT,42.0
51,BRIAN,MITCHELL,SUPPORT,35.0
533,WAYNE,SCHERER,SUPPORT,30.0
448,ROBERT,LOCKART,SUPPORT,25.0
185,GEORGE,OKEEFE,SUPPORT,25.0
510,SUE ANN,LORIG,SUPPORT,25.0
355,MARK,SLABAUGH,SUPPORT,25.0
540,WILLIAM,SANTSCHI,SUPPORT,25.0
430,RICH,GOLDBERG,SUPPORT,25.0
358,MARSTON,MEDLOCK,SUPPORT,0.0
497,STEPHANIE,WARREN-SAMARIPA,SUPPORT,0.0
16,AMIRGHASEM,SAMIMI-ARDESTAN,SUPPORT,0.0
136,DAVID,WOOD,SUPPORT,0.0

In [40]:
prop66= props[props.prop_name=="PROPOSITION 066- DEATH PENALTY. PROCEDURES. INITIATIVE STATUTE."]

In [41]:
prop66.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
86,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,468,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",SUPPORT
87,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,469,1302403,CALIFORNIA CORRECTIONAL PEACE OFFICERS ASSOCIA...,SUPPORT
88,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,470,1385745,FUND FOR POLICY REFORM (NONPROFIT 501(C)(4)),OPPOSE
89,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,471,1386494,PROTEUS ACTION LEAGUE NON-PROFIT 501 (C)(4) OR...,OPPOSE
90,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,472,1380590,"YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...",OPPOSE

In [42]:
prop66.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9 entries, 86 to 94
Data columns (total 8 columns):
ocd_prop_id               9 non-null object
calaccess_prop_id         9 non-null int64
ccdc_prop_id              9 non-null int64
prop_name                 9 non-null object
ccdc_committee_id         9 non-null int64
calaccess_committee_id    9 non-null int64
committee_name            9 non-null object
committee_position        9 non-null object
dtypes: int64(4), object(4)
memory usage: 648.0+ bytes

In [43]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [44]:
merge2= pd.merge(prop66, contribs, on="calaccess_committee_id")

In [45]:
merge2.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,468,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",SUPPORT,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2012262,2015-09-03,SACRAMENTO COUNTY DEPUTY SHERIFFS' ASSOCIATION,NaN,SACRAMENTO,CA,95814,NaN,NaN,False,60000.0
1,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,468,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",SUPPORT,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2012262,2015-09-11,SAN FRANCISCO POLICE OFFICER ASSOCIATION,NaN,SAN FRANCISCO,CA,94103,NaN,NaN,False,60000.0
2,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,468,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",SUPPORT,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2012262,2015-09-14,SAN DIEGANS AGAINST CRIME PAC,NaN,ENCINITAS,CA,92024,NaN,NaN,False,25000.0
3,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,468,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",SUPPORT,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2012262,2015-09-17,SAN DIEGO COUNTY DA ASSOCIATION,NaN,SAN DIEGO,CA,92101,NaN,NaN,False,25000.0
4,ocd-contest/19eca91d-e494-4ee0-a345-8f96eeec8a3e,1381724,85,PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...,468,1346266,"CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...",SUPPORT,"CALIFORNIANS FOR JUSTICE AND PUBLIC SAFETY, NO...",2012262,2015-09-21,ASSOCIATION OF ORANGE COUNTY DEPUTY SHERIFFS I...,NaN,SACRAMENTO,CA,95814,NaN,NaN,False,20000.0

In [52]:
merge2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33828 entries, 0 to 33827
Data columns (total 20 columns):
ocd_prop_id                     33828 non-null object
calaccess_prop_id               33828 non-null int64
ccdc_prop_id                    33828 non-null int64
prop_name                       33828 non-null object
ccdc_committee_id               33828 non-null int64
calaccess_committee_id          33828 non-null int64
committee_name_x                33828 non-null object
committee_position              33828 non-null object
committee_name_y                33828 non-null object
calaccess_filing_id             33828 non-null int64
date_received                   33828 non-null object
contributor_lastname            33824 non-null object
contributor_firstname           33288 non-null object
contributor_city                33825 non-null object
contributor_state               33824 non-null object
contributor_zip                 33825 non-null object
contributor_employer            33132 non-null object
contributor_occupation          33286 non-null object
contributor_is_self_employed    33828 non-null bool
amount                          33828 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 5.2+ MB

In [50]:
merge2.amount.sum()

34291239.299999997

In [54]:
merge2.committee_position.value_counts()

SUPPORT    29633
OPPOSE      4195
Name: committee_position, dtype: int64

In [62]:
support=merge2[merge2.committee_position == "SUPPORT"]

In [63]:
oppose=merge2[merge2.committee_position == "OPPOSE"]

In [64]:
support.amount.sum()

16836069.809999999

In [65]:
oppose.amount.sum()

17455169.490000002

In [66]:
support.amount.sum()/merge2.amount.sum()

0.49097291768046425

In [67]:
merge2.groupby("committee_name_x").amount.sum().reset_index().sort_values("amount", ascending=False)

                                    committee_name_x        amount
1  CALIFORNIANS TO MEND, NOT END, THE DEATH PENAL...  8.387852e+06
0  CALIFORNIA CORRECTIONAL PEACE OFFICERS ASSOCIA...  8.343218e+06
7  YES ON 62, NO ON 66. REPLACE THE COSTLY, FAILE...  7.621678e+06
2       FUND FOR POLICY REFORM (NONPROFIT 501(C)(4))  6.140000e+06
3  MILLION VOTER PROJECT ACTION FUND - YES ON 55,...  2.110000e+06
4  NO ON PROP 66, CALIFORNIANS FOR FAIR JUSTICE, ...  1.486701e+06
6  SAN FRANCISCO POLICE OFFICERS ASSOCIATION ISSU...  1.050000e+05
5  PROTEUS ACTION LEAGUE NON-PROFIT 501 (C)(4) OR...  9.679012e+04

In [73]:
merge2.groupby(["contributor_lastname", "contributor_firstname", "committee_position"]).amount.sum().reset_index().sort_values("amount", ascending=False).head()

      contributor_lastname contributor_firstname committee_position     amount
26001               STEYER                THOMAS             OPPOSE  1750000.0
17392              MCKEOWN              NICHOLAS             OPPOSE  1500000.0
11693             HASTINGS                  REED             OPPOSE  1000000.0
10634               GRAHAM                  PAUL             OPPOSE   500000.0
7208                 DOERR               L. JOHN             OPPOSE   500000.0

In [75]:
merge2.groupby(["contributor_lastname", "contributor_firstname", "contributor_occupation", "contributor_employer", "committee_position"]).amount.sum().reset_index().sort_values("amount", ascending=False).head()

,contributor_lastname,contributor_firstname,contributor_occupation,contributor_employer,committee_position,amount
26018,STEYER,THOMAS,FOUNDER,FARALLON CAPITAL,OPPOSE,1750000.0
17399,MCKEOWN,NICHOLAS,PROFESSOR,STANFORD UNIVERSITY,OPPOSE,1500000.0
11694,HASTINGS,REED,CHIEF EXECUTIVE OFFICER,NETFLIX,OPPOSE,1000000.0
7211,DOERR,L. JOHN,VENTURE CAPITALIST,KLEINER PERKINS CAUFIELD & BYERS,OPPOSE,500000.0
10639,GRAHAM,PAUL,CHIEF EXECUTIVE OFFICER,Y COMBINATOR,OPPOSE,500000.0